version: 0.0
os: linux
files: 
  - source: source
  - destination: /webapps/node
hooks:
  BeforeInstall:
    - location: Scripts/installdeps.sh
  ApplicationStart:
    - location: Scripts/startapp.sh
